apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: ubuntu:latest
        name: guestbook-ui
        command: ["bash"]
        args:
        - -c
        - sleep infinity
        ports:
        - containerPort: 80
