apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      # - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
      - image: centos:7
        command: ["sleep"]
        args: ["infinity"]
        name: guestbook-ui
        ports:
        - containerPort: 80
        securityContext:
          privileged: true

