namePrefix: sample-kustomize-
commonLabels:
  project: sample-kustomize-app
resources:
- https://github.com/hirokuni-kitahara/sample-kustomize-base.git
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
