apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sample-deployment
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - image: ubuntu:latest
        name: sample-deployment
        command: ["bash"]
        args:
        - -c
        - sleep infinity
        ports:
        - containerPort: 80
